include_guard()

find_program(CCACHE_EXECUTABLE NAMES ccache)
if(CCACHE_EXECUTABLE)
  message(STATUS "ccache found -- ${CCACHE_EXECUTABLE}")
else()
  message(STATUS "ccache not found")
endif()

find_program(CLANG_TIDY_EXECUTABLE NAMES clang-tidy)
if(CLANG_TIDY_EXECUTABLE)
  message(STATUS "clang-tidy found -- ${CLANG_TIDY_EXECUTABLE}")
else()
  message(STATUS "clang-tidy not found")
endif()

find_program(CLANG_FORMAT_EXECUTABLE NAMES clang-format)
if(CLANG_FORMAT_EXECUTABLE)
  message(STATUS "clang-format found -- ${CLANG_FORMAT_EXECUTABLE}")
else()
  message(STATUS "clang-format not found")
endif()

find_program(IWYU_EXECUTABLE NAMES include-what-you-use)
if(IWYU_EXECUTABLE)
  message(STATUS "include-what-you-use found - ${IWYU_EXECUTABLE}")
else()
  message(STATUS "include-what-you-use not found")
endif()

find_package(Doxygen OPTIONAL_COMPONENTS dot)
