include_guard()

find_program(CCACHE NAMES ccache)
if(CCACHE)
  message(STATUS "ccache found -- ${CCACHE}")
else()
  message(STATUS "ccache not found")
endif()

find_program(CLANG_TIDY NAMES clang-tidy)
if(CLANG_TIDY)
  message(STATUS "clang-tidy found -- ${CLANG_TIDY}")
else()
  message(STATUS "clang-tidy not found")
endif()

find_program(CLANG_FORMAT NAMES clang-format)
if(CLANG_FORMAT)
  message(STATUS "clang-format found -- ${CLANG_FORMAT}")
else()
  message(STATUS "clang-format not found")
endif()

find_program(IWYU NAMES include-what-you-use)
if(IWYU)
  message(STATUS "include-what-you-use found - ${IWYU}")
else()
  message(STATUS "include-what-you-use not found")
endif()
